### ISSUE TITLE
Description.md can be empty so suppress error

### ISSUE THREAD

**Issue by klg71** [danakuban/docsGradlePlugin#6]
Hey danakuban :)

I really like the plugin and we use it extensively in out project to ensure proper documentation.

I noticed a small bug that is in my eyes probably unwanted.
You can create an empty `description.md` and the compile error disappears. I would suggest to also check if the file is empty.

Best Regards

**Comment by danakuban** [comment]
Hey klg71 :)

Thanks for the hint! I'm going to fix this in fact unwanted behavior. Glad to hear that the plugin is of good use for you!

Best regards
